# Define Parameter Names

# Create a data frame that tracks matches between NADP precipitation parameters
# and CSLS lake and wells SWIMS datasets

library(usethis)
param_names <- data_frame(NADP_param = c("",
                                         "",
                                         "Br",
                                         "Ca",
                                         "Cl",
                                         "Conduc",
                                         "",
                                         "",
                                         "Mg",
                                         "",
                                         "",
                                         "NH4",
                                         "",
                                         "NO3",
                                         "ph",
                                         "",
                                         "K",
                                         "",
                                         "Na",
                                         "SO4"),
                          CSLS_param = c("ALKALINITY TOTAL CACO3",
                                         "ALUMINUM,TOTAL RECOVERABLE",
                                         "",
                                         "CALCIUM TOTAL RECOVERABLE",
                                         "CHLORIDE",
                                         "CONDUCTIVITY, UMHOS/CM @ 25C",
                                         "HARDNESS TOTAL RECOVERABLE CALCULATION",
                                         "IRON TOTAL RECOVERABLE",
                                         "MAGNESIUM TOTAL RECOVERABLE",
                                         "MANGANESE, TOTAL RECOVERABLE",
                                         "NITROGEN NH3-N DISS",
                                         "",
                                         "NITROGEN NO3+NO2 DISS (AS N)",
                                         "",
                                         "PH LAB",
                                         "PHOSPHORUS TOTAL",
                                         "POTASSIUM TOTAL RECOVERABLE",
                                         "SILICA, DISSOLVED (MG/L AS SI02)",
                                         "SODIUM TOTAL RECOVERABLE",
                                         "SULFATE TOTAL"),
                          CSLS_names = c("Alkalinity Total CaCO3",
                                         "Total Recoverable Aluminum",
                                         "",
                                         "Total Recoverable Calcium",
                                         "Chloride",
                                         "Conductivity",
                                         "Total Recoverable Hardness",
                                         "Total Recoverable Iron",
                                         "Total Recoverable Magnesium",
                                         "Total Recoverable Manganese",
                                         "Dissolved Ammonia as Nitrogen",
                                         "",
                                         "Dissolved Nitrate/Nitrite as Nitrogen",
                                         "",
                                         "pH",
                                         "Total Phosphorus",
                                         "Total Recoverable Potassium",
                                         "Dissolved Silica as SiO2",
                                         "Total Recoverable Sodium",
                                         "Total Sulfate"))

use_data(param_names, overwrite = TRUE, compress = "xz")
