---
title: "CSLS Water Chem Visualization: Lake Stratification"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Lake Temp and DO}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, echo=FALSE, eval=TRUE, warning=FALSE, message=FALSE}
library(knitr)
library(CSLSchem)
library(dplyr)
library(ggplot2)
library(extrafont)

text_size    <- 12
lakes        <- c("Pleasant", "Long", "Plainfield")
water_chem   <- CSLSdata::water_chem

plot_HOBO <- function(lake, water_chem) {
  ltmp     <- filter_parameter(water_chem, "TEMPERATURE HOBO") %>%
              filter(.data$lake == !!lake,
                     !is.na(.data$result)) %>%
              group_by(.data$date) %>%
              mutate(min_depth = min(.data$depth1_m),
                     max_depth = max(.data$depth1_m)) %>%
              ungroup() %>%
              filter(.data$depth1_m == .data$min_depth |
                       .data$depth1_m == .data$max_depth) %>%
              mutate(depth = ifelse(.data$depth1_m > 2,
                                    "Bottom", "Surface")) %>%
              select(.data$date, .data$result, .data$depth)
  DO     <- filter_parameter(water_chem, "DISSOLVED OXYGEN HOBO") %>%
            filter(.data$lake == !!lake,
                     !is.na(.data$result)) %>%
              group_by(.data$date) %>%
              mutate(min_depth = min(.data$depth1_m),
                     max_depth = max(.data$depth1_m)) %>%
              ungroup() %>%
              filter(.data$depth1_m == .data$min_depth |
                       .data$depth1_m == .data$max_depth) %>%
              mutate(depth = ifelse(.data$depth1_m > 3,
                                    "Bottom", "Surface")) %>%
              select(.data$date, .data$result, .data$depth)
  
  plot_obj <- ggplot() +
              geom_line(data = ltmp,
                        aes(x = date, 
                            y = result,
                            color = depth,
                            linetype = "Temperature"),
                        size = 1) +
              geom_line(data = DO,
                        aes(x = date, 
                            y = result*2,
                            color = depth,
                            linetype = "DO")) +
              scale_x_datetime(breaks = "2 months",
                               date_labels = "%b %y") +
              labs(x = "", 
                   y = "Temperature (deg C)",
                   title = sprintf("%s Lake", lake)) +
              scale_y_continuous(sec.axis = sec_axis(~./2, 
                                                     name = "Dissolved Oxygen (mg/L)")) +
              scale_color_brewer(name = "",
                                 palette = "Paired") +
              scale_linetype_manual(name = "",
                                    breaks = c("Temperature", "DO"),
                                    values = c("solid", "dotted")) +
              theme_bw() +
              theme(text = element_text(family = "Segoe UI Semilight",
                                        size = text_size),
                    panel.grid.major = element_blank(),
                    panel.grid.minor = element_blank(),
                    legend.position = "top")
  return(plot_obj)
}

plot_field <- function(lake, water_chem) {
  ltmp     <- filter_parameter(water_chem, "TEMPERATURE FIELD") %>%
              filter(.data$lake == !!lake,
                     !is.na(.data$result)) %>%
              group_by(.data$date) %>%
              mutate(min_depth = min(.data$depth1_m),
                     max_depth = max(.data$depth1_m)) %>%
              ungroup() %>%
              filter(.data$depth1_m == .data$min_depth |
                       .data$depth1_m == .data$max_depth) %>%
              mutate(depth = ifelse(.data$depth1_m > 1.5,
                                    "Bottom", "Surface")) %>%
              select(.data$date, .data$result, .data$depth)
  DO     <- filter_parameter(water_chem, "DISSOLVED OXYGEN FIELD") %>%
            filter(.data$lake == !!lake,
                     !is.na(.data$result)) %>%
              group_by(.data$date) %>%
              mutate(min_depth = min(.data$depth1_m),
                     max_depth = max(.data$depth1_m)) %>%
              ungroup() %>%
              filter(.data$depth1_m == .data$min_depth |
                       .data$depth1_m == .data$max_depth) %>%
              mutate(depth = ifelse(.data$depth1_m > 1.5,
                                    "Bottom", "Surface")) %>%
              select(.data$date, .data$result, .data$depth)
  
  plot_obj <- ggplot() +
              geom_line(data = ltmp,
                        aes(x = date, 
                            y = result,
                            color = depth,
                            linetype = "Temperature"),
                        size = 1) +
              geom_line(data = DO,
                        aes(x = date, 
                            y = result*2,
                            color = depth,
                            linetype = "DO"),
                        size = 1) +
              scale_x_datetime(breaks = "2 months",
                               date_labels = "%b %y") +
              labs(x = "", 
                   y = "Temperature (deg C)",
                   title = sprintf("%s Lake", lake)) +
              scale_y_continuous(sec.axis = sec_axis(~./2, 
                                                     name = "Dissolved Oxygen (mg/L)")) +
              scale_color_brewer(name = "",
                                 palette = "Paired") +
              scale_linetype_manual(name = "",
                                    breaks = c("Temperature", "DO"),
                                    values = c("solid", "dotted")) +
              theme_bw() +
              theme(text = element_text(family = "Segoe UI Semilight",
                                        size = text_size),
                    panel.grid.major = element_blank(),
                    panel.grid.minor = element_blank(),
                    legend.position = "top")
  return(plot_obj)
}

```

# Temperature and DO Line Plots

```{r lines, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE, fig.width=7, fig.height=5, fig.align="center"}
plot_HOBO("Pleasant", water_chem)
plot_field("Long", water_chem)
plot_field("Plainfield", water_chem)

```
