---
title: "CSLS Water Chem Budget"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{chem_budget}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
library(CSLSchem)
library(dplyr)
library(extrafont)
library(ggplot2)
library(reshape2)
library(kableExtra)
library(NISTunits)

text_size  <- 12
mass_fluxes1 <- calculate_solute_balance(annual = TRUE)
mass_fluxes1 <- mass_fluxes1 %>%
                group_by(.data$lake, .data$parameter) %>%
                mutate(pcnt = round(100*.data$mass_kg/
                              (.data$mass_kg[.data$site_type=="P"]+
                                 .data$mass_kg[.data$site_type=="GWin"]),1)) %>%
                ungroup()

mass_fluxes2 <- calculate_solute_balance()
mass_fluxes2 <- mass_fluxes2 %>%
                group_by(lake = .data$lake,
                         parameter = .data$parameter,
                         site_type = .data$site_type) %>%
                summarise(mass_kg = sum(.data$mass_kg)) %>%
                ungroup()
mass_fluxes2 <- mass_fluxes2 %>%
                group_by(.data$lake, .data$parameter) %>%
                mutate(pcnt = round(100*.data$mass_kg/
                              (.data$mass_kg[.data$site_type=="P"]+
                                 .data$mass_kg[.data$site_type=="GWin"]),1)) %>%
                ungroup()


mass_fluxes3 <- calculate_solute_balance(chem_tracer = "MAGNESIUM TOTAL RECOVERABLE")
mass_fluxes3 <- mass_fluxes3 %>%
                group_by(lake = .data$lake,
                         parameter = .data$parameter,
                         site_type = .data$site_type) %>%
                summarise(mass_kg = sum(.data$mass_kg)) %>%
                ungroup()
mass_fluxes3 <- mass_fluxes3 %>%
                group_by(.data$lake, .data$parameter) %>%
                mutate(pcnt = round(100*.data$mass_kg/
                              (.data$mass_kg[.data$site_type=="P"]+
                                 .data$mass_kg[.data$site_type=="GWin"]),1)) %>%
                ungroup()

plot_solutes <- function(mass_fluxes, 
                         lake, 
                         text_size, 
                         color_vals = c("#1F78B4", "#33A02C", "#B2DF8A",
                                        "#FB9A99", "#E31A1C")) {
  plot_df <- mass_fluxes %>% filter(.data$lake == !!lake)
  plot_obj <- ggplot(plot_df) +
              geom_col(aes(x = .data$site_type,
                           y = .data$mass_kg,
                           fill = .data$site_type)) +
              facet_wrap(~parameter, scales = "free") +
              labs(x = "", y = "Solute Mass (kg)") +
              scale_fill_manual(name = "",
                                 values = color_vals) +
              theme_bw() +
              theme(text = element_text(family = "Segoe UI Semilight",
                                        size = text_size),
                    panel.grid.major = element_blank(),
                    panel.grid.minor = element_blank(),
                    legend.position = "top")
  
  return(plot_obj)
}

format_table <- function(mass_fluxes, lake) {
  table_df <- mass_fluxes %>% 
              filter(.data$lake == !!lake) %>%
              select(.data$site_type, .data$parameter, .data$pcnt)
  table_df <- dcast(table_df, parameter~site_type, value.var = "pcnt")
  return(table_df)
}


```

## Pleasant Lake

### Annual

```{r psnt1, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE, fig.width=8.5, fig.height=5, fig.align="center"}
lake <- "Pleasant"
plot_solutes(mass_fluxes1, lake, text_size)
kableExtra::kable(format_table(mass_fluxes1, lake), 
                  caption = sprintf("Percent of Total Inflow: %s Lake", lake))
```

### Monthly (Summed to Annual)

```{r psnt2, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE, fig.width=8.5, fig.height=5, fig.align="center"}
plot_solutes(mass_fluxes2, lake, text_size)
kableExtra::kable(format_table(mass_fluxes2, lake), 
                  caption = sprintf("Percent of Total Inflow: %s Lake", lake))
```

### Monthly (Summed to Annual) w/Mg used for water balance

```{r psnt3, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE, fig.width=8.5, fig.height=5, fig.align="center"}
plot_solutes(mass_fluxes3, lake, text_size)
kableExtra::kable(format_table(mass_fluxes3, lake), 
                  caption = sprintf("Percent of Total Inflow: %s Lake", lake))
```


## Long Lake

### Annual

```{r long1, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE, fig.width=8.5, fig.height=5, fig.align="center"}
lake <- "Long"
plot_solutes(mass_fluxes1, lake, text_size)
kableExtra::kable(format_table(mass_fluxes1, lake), 
                  caption = sprintf("Percent of Total Inflow: %s Lake", lake))
```

### Monthly (Summed to Annual)

```{r long2, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE, fig.width=8.5, fig.height=5, fig.align="center"}
plot_solutes(mass_fluxes2, lake, text_size)
kableExtra::kable(format_table(mass_fluxes2, lake), 
                  caption = sprintf("Percent of Total Inflow: %s Lake", lake))
```

### Monthly (Summed to Annual) w/Mg used for water balance

```{r long3, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE, fig.width=8.5, fig.height=5, fig.align="center"}
plot_solutes(mass_fluxes3, lake, text_size)
kableExtra::kable(format_table(mass_fluxes3, lake), 
                  caption = sprintf("Percent of Total Inflow: %s Lake", lake))
```

## Plainfield Lake

### Annual

```{r pfl1, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE, fig.width=8.5, fig.height=5, fig.align="center"}
lake <- "Plainfield"
plot_solutes(mass_fluxes1, lake, text_size)
kableExtra::kable(format_table(mass_fluxes1, lake), 
                  caption = sprintf("Percent of Total Inflow: %s Lake", lake))
```

### Monthly (Summed to Annual)

```{r pfl2, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE, fig.width=8.5, fig.height=5, fig.align="center"}
plot_solutes(mass_fluxes2, lake, text_size)
kableExtra::kable(format_table(mass_fluxes2, lake), 
                  caption = sprintf("Percent of Total Inflow: %s Lake", lake))
```

### Monthly (Summed to Annual) w/Mg used for water balance

```{r pfl3, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE, fig.width=8.5, fig.height=5, fig.align="center"}
plot_solutes(mass_fluxes3, lake, text_size)
kableExtra::kable(format_table(mass_fluxes3, lake), 
                  caption = sprintf("Percent of Total Inflow: %s Lake", lake))
```
